# Generated by Django 2.1 on 2018-08-28 18:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Batsman',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=250)),
                ('lastName', models.CharField(max_length=250)),
                ('run_rate', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Bowler',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=250)),
                ('lastName', models.CharField(max_length=250)),
                ('countryName', models.CharField(max_length=250)),
                ('country_flag', models.CharField(max_length=100)),
                ('over_played', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='batsman',
            name='bowler',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cricket.Bowler'),
        ),
    ]
